package PMSystem;


/**
* PMSystem/MessageOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PMSystem.idl
* domingo 27 de noviembre de 2011 08H25' CST
*/

public interface MessageOperations 
{
  boolean sendMessage (int sender, int receiver, String subject, String message, String date, String state);
  boolean updateState (int id, String state);
  boolean trash (int id);
  boolean restore (int id);
  boolean delete (int id);
  int areNewMessages (int receiver);
  PMSystem.MessageData getMessage (int id);
  PMSystem.MessageData[] getTrashMessages (int id_user);
  PMSystem.MessageData[] getInboxMessages (int id_user);
  PMSystem.MessageData[] getOutboxMessages (int id_user);
} // interface MessageOperations
