package PMSystem;


/**
* PMSystem/OnlineUsersHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PMSystem.idl
* domingo 27 de noviembre de 2011 08H25' CST
*/

abstract public class OnlineUsersHelper
{
  private static String  _id = "IDL:PMSystem/OnlineUsers:1.0";

  public static void insert (org.omg.CORBA.Any a, PMSystem.UsersOnlineInfo[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static PMSystem.UsersOnlineInfo[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = PMSystem.UsersOnlineInfoHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (PMSystem.OnlineUsersHelper.id (), "OnlineUsers", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static PMSystem.UsersOnlineInfo[] read (org.omg.CORBA.portable.InputStream istream)
  {
    PMSystem.UsersOnlineInfo value[] = null;
    int _len0 = istream.read_long ();
    value = new PMSystem.UsersOnlineInfo[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = PMSystem.UsersOnlineInfoHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, PMSystem.UsersOnlineInfo[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      PMSystem.UsersOnlineInfoHelper.write (ostream, value[_i0]);
  }

}
