package PMSystem;


/**
* PMSystem/ProjectData.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PMSystem.idl
* domingo 27 de noviembre de 2011 08H25' CST
*/

public final class ProjectData implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public int id_user = (int)0;
  public String user_name = null;
  public String name = null;
  public String description = null;
  public String start_date = null;
  public String end_date = null;
  public String state = null;

  public ProjectData ()
  {
  } // ctor

  public ProjectData (int _id, int _id_user, String _user_name, String _name, String _description, String _start_date, String _end_date, String _state)
  {
    id = _id;
    id_user = _id_user;
    user_name = _user_name;
    name = _name;
    description = _description;
    start_date = _start_date;
    end_date = _end_date;
    state = _state;
  } // ctor

} // class ProjectData
