package PMSystem;


/**
* PMSystem/ProjectsBasicData.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PMSystem.idl
* domingo 27 de noviembre de 2011 08H25' CST
*/

public final class ProjectsBasicData implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String name = null;

  public ProjectsBasicData ()
  {
  } // ctor

  public ProjectsBasicData (int _id, String _name)
  {
    id = _id;
    name = _name;
  } // ctor

} // class ProjectsBasicData
