package PMSystem;


/**
* PMSystem/ReportOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PMSystem.idl
* domingo 27 de noviembre de 2011 08H25' CST
*/

public interface ReportOperations 
{
  PMSystem.GeneralReportData getGeneralReportData ();
  int getLogins (String date, String datelimit);
  PMSystem.Configuration getConfig ();
  boolean setConfig (String language, String theme);
  void addMissingTranslation (String translation);
} // interface ReportOperations
