package PMSystem;


/**
* PMSystem/ReportPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PMSystem.idl
* domingo 27 de noviembre de 2011 08H25' CST
*/

public abstract class ReportPOA extends org.omg.PortableServer.Servant
 implements PMSystem.ReportOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getGeneralReportData", new java.lang.Integer (0));
    _methods.put ("getLogins", new java.lang.Integer (1));
    _methods.put ("getConfig", new java.lang.Integer (2));
    _methods.put ("setConfig", new java.lang.Integer (3));
    _methods.put ("addMissingTranslation", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // PMSystem/Report/getGeneralReportData
       {
         PMSystem.GeneralReportData $result = null;
         $result = this.getGeneralReportData ();
         out = $rh.createReply();
         PMSystem.GeneralReportDataHelper.write (out, $result);
         break;
       }

       case 1:  // PMSystem/Report/getLogins
       {
         String date = in.read_string ();
         String datelimit = in.read_string ();
         int $result = (int)0;
         $result = this.getLogins (date, datelimit);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // PMSystem/Report/getConfig
       {
         PMSystem.Configuration $result = null;
         $result = this.getConfig ();
         out = $rh.createReply();
         PMSystem.ConfigurationHelper.write (out, $result);
         break;
       }

       case 3:  // PMSystem/Report/setConfig
       {
         String language = in.read_string ();
         String theme = in.read_string ();
         boolean $result = false;
         $result = this.setConfig (language, theme);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // PMSystem/Report/addMissingTranslation
       {
         String translation = in.read_string ();
         this.addMissingTranslation (translation);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:PMSystem/Report:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Report _this() 
  {
    return ReportHelper.narrow(
    super._this_object());
  }

  public Report _this(org.omg.CORBA.ORB orb) 
  {
    return ReportHelper.narrow(
    super._this_object(orb));
  }


} // class ReportPOA
