package PMSystem;

/**
* PMSystem/ReportHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PMSystem.idl
* domingo 27 de noviembre de 2011 08H25' CST
*/

public final class ReportHolder implements org.omg.CORBA.portable.Streamable
{
  public PMSystem.Report value = null;

  public ReportHolder ()
  {
  }

  public ReportHolder (PMSystem.Report initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PMSystem.ReportHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PMSystem.ReportHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PMSystem.ReportHelper.type ();
  }

}
