package PMSystem;


/**
* PMSystem/SessionDataHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PMSystem.idl
* domingo 27 de noviembre de 2011 08H25' CST
*/

public final class SessionDataHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public SessionDataHolder ()
  {
  }

  public SessionDataHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PMSystem.SessionDataHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PMSystem.SessionDataHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PMSystem.SessionDataHelper.type ();
  }

}
