package PMSystem;


/**
* PMSystem/TaskOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PMSystem.idl
* domingo 27 de noviembre de 2011 08H25' CST
*/

public interface TaskOperations 
{
  int setTask (int id_project, String[] users, String title, String description, String start_date, String end_date, int progress, String priority, String state);
  int updateTask (int id, int id_project, String[] users, String title, String description, String start_date, String end_date, int progress, String priority, String state);
  int updateProgress (int id, int progress, String notes, String state);
  PMSystem.TasksBasicData[] getAllTasks ();
  PMSystem.TaskData getTask (int id);
  PMSystem.TaskData[] getTasks (String str);
  PMSystem.TaskData[] getTasksByUser (int id);
  boolean trash (int id);
  boolean delete (int id);
  boolean restore (int id);
} // interface TaskOperations
