package PMSystem;

/**
* PMSystem/UsersOnlineInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PMSystem.idl
* domingo 27 de noviembre de 2011 08H25' CST
*/

public final class UsersOnlineInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public PMSystem.UsersOnlineInfo value = null;

  public UsersOnlineInfoHolder ()
  {
  }

  public UsersOnlineInfoHolder (PMSystem.UsersOnlineInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PMSystem.UsersOnlineInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PMSystem.UsersOnlineInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PMSystem.UsersOnlineInfoHelper.type ();
  }

}
