package PMSystem;

/**
* PMSystem/UsersBasicDataHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PMSystem.idl
* domingo 27 de noviembre de 2011 08H25' CST
*/

public final class UsersBasicDataHolder implements org.omg.CORBA.portable.Streamable
{
  public PMSystem.UsersBasicData value = null;

  public UsersBasicDataHolder ()
  {
  }

  public UsersBasicDataHolder (PMSystem.UsersBasicData initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PMSystem.UsersBasicDataHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PMSystem.UsersBasicDataHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PMSystem.UsersBasicDataHelper.type ();
  }

}
