package PMSystem;


/**
* PMSystem/UsersBasicData.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PMSystem.idl
* domingo 27 de noviembre de 2011 08H25' CST
*/

public final class UsersBasicData implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String username = null;

  public UsersBasicData ()
  {
  } // ctor

  public UsersBasicData (int _id, String _username)
  {
    id = _id;
    username = _username;
  } // ctor

} // class UsersBasicData
