package PMSystem;

/**
* PMSystem/UserHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PMSystem.idl
* domingo 27 de noviembre de 2011 08H25' CST
*/

public final class UserHolder implements org.omg.CORBA.portable.Streamable
{
  public PMSystem.User value = null;

  public UserHolder ()
  {
  }

  public UserHolder (PMSystem.User initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PMSystem.UserHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PMSystem.UserHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PMSystem.UserHelper.type ();
  }

}
