package PMSystem;


/**
* PMSystem/Configuration.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PMSystem.idl
* domingo 27 de noviembre de 2011 08H59' CST
*/

public final class Configuration implements org.omg.CORBA.portable.IDLEntity
{
  public String language = null;
  public String theme = null;

  public Configuration ()
  {
  } // ctor

  public Configuration (String _language, String _theme)
  {
    language = _language;
    theme = _theme;
  } // ctor

} // class Configuration
