package PMSystem;


/**
* PMSystem/GeneralReportDataHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PMSystem.idl
* domingo 27 de noviembre de 2011 08H59' CST
*/

abstract public class GeneralReportDataHelper
{
  private static String  _id = "IDL:PMSystem/GeneralReportData:1.0";

  public static void insert (org.omg.CORBA.Any a, PMSystem.GeneralReportData that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static PMSystem.GeneralReportData extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [24];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "total_users",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[1] = new org.omg.CORBA.StructMember (
            "total_administrators",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[2] = new org.omg.CORBA.StructMember (
            "total_normalusers",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[3] = new org.omg.CORBA.StructMember (
            "total_men",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[4] = new org.omg.CORBA.StructMember (
            "total_women",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[5] = new org.omg.CORBA.StructMember (
            "total_activeusers",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[6] = new org.omg.CORBA.StructMember (
            "total_inactiveusers",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[7] = new org.omg.CORBA.StructMember (
            "total_logins",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[8] = new org.omg.CORBA.StructMember (
            "last_login",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[9] = new org.omg.CORBA.StructMember (
            "total_projects",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[10] = new org.omg.CORBA.StructMember (
            "total_activeprojects",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[11] = new org.omg.CORBA.StructMember (
            "total_inactiveprojects",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[12] = new org.omg.CORBA.StructMember (
            "last_project",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[13] = new org.omg.CORBA.StructMember (
            "total_tasks",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[14] = new org.omg.CORBA.StructMember (
            "total_started",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[15] = new org.omg.CORBA.StructMember (
            "total_paused",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[16] = new org.omg.CORBA.StructMember (
            "total_stoped",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[17] = new org.omg.CORBA.StructMember (
            "total_finished",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[18] = new org.omg.CORBA.StructMember (
            "total_inactive",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[19] = new org.omg.CORBA.StructMember (
            "total_urgent",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[20] = new org.omg.CORBA.StructMember (
            "total_high",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[21] = new org.omg.CORBA.StructMember (
            "total_medium",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[22] = new org.omg.CORBA.StructMember (
            "total_low",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[23] = new org.omg.CORBA.StructMember (
            "last_task",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (PMSystem.GeneralReportDataHelper.id (), "GeneralReportData", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static PMSystem.GeneralReportData read (org.omg.CORBA.portable.InputStream istream)
  {
    PMSystem.GeneralReportData value = new PMSystem.GeneralReportData ();
    value.total_users = istream.read_long ();
    value.total_administrators = istream.read_long ();
    value.total_normalusers = istream.read_long ();
    value.total_men = istream.read_long ();
    value.total_women = istream.read_long ();
    value.total_activeusers = istream.read_long ();
    value.total_inactiveusers = istream.read_long ();
    value.total_logins = istream.read_long ();
    value.last_login = istream.read_string ();
    value.total_projects = istream.read_long ();
    value.total_activeprojects = istream.read_long ();
    value.total_inactiveprojects = istream.read_long ();
    value.last_project = istream.read_string ();
    value.total_tasks = istream.read_long ();
    value.total_started = istream.read_long ();
    value.total_paused = istream.read_long ();
    value.total_stoped = istream.read_long ();
    value.total_finished = istream.read_long ();
    value.total_inactive = istream.read_long ();
    value.total_urgent = istream.read_long ();
    value.total_high = istream.read_long ();
    value.total_medium = istream.read_long ();
    value.total_low = istream.read_long ();
    value.last_task = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, PMSystem.GeneralReportData value)
  {
    ostream.write_long (value.total_users);
    ostream.write_long (value.total_administrators);
    ostream.write_long (value.total_normalusers);
    ostream.write_long (value.total_men);
    ostream.write_long (value.total_women);
    ostream.write_long (value.total_activeusers);
    ostream.write_long (value.total_inactiveusers);
    ostream.write_long (value.total_logins);
    ostream.write_string (value.last_login);
    ostream.write_long (value.total_projects);
    ostream.write_long (value.total_activeprojects);
    ostream.write_long (value.total_inactiveprojects);
    ostream.write_string (value.last_project);
    ostream.write_long (value.total_tasks);
    ostream.write_long (value.total_started);
    ostream.write_long (value.total_paused);
    ostream.write_long (value.total_stoped);
    ostream.write_long (value.total_finished);
    ostream.write_long (value.total_inactive);
    ostream.write_long (value.total_urgent);
    ostream.write_long (value.total_high);
    ostream.write_long (value.total_medium);
    ostream.write_long (value.total_low);
    ostream.write_string (value.last_task);
  }

}
