package PMSystem;


/**
* PMSystem/GeneralReportData.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PMSystem.idl
* domingo 27 de noviembre de 2011 08H59' CST
*/

public final class GeneralReportData implements org.omg.CORBA.portable.IDLEntity
{
  public int total_users = (int)0;
  public int total_administrators = (int)0;
  public int total_normalusers = (int)0;
  public int total_men = (int)0;
  public int total_women = (int)0;
  public int total_activeusers = (int)0;
  public int total_inactiveusers = (int)0;
  public int total_logins = (int)0;
  public String last_login = null;
  public int total_projects = (int)0;
  public int total_activeprojects = (int)0;
  public int total_inactiveprojects = (int)0;
  public String last_project = null;
  public int total_tasks = (int)0;
  public int total_started = (int)0;
  public int total_paused = (int)0;
  public int total_stoped = (int)0;
  public int total_finished = (int)0;
  public int total_inactive = (int)0;
  public int total_urgent = (int)0;
  public int total_high = (int)0;
  public int total_medium = (int)0;
  public int total_low = (int)0;
  public String last_task = null;

  public GeneralReportData ()
  {
  } // ctor

  public GeneralReportData (int _total_users, int _total_administrators, int _total_normalusers, int _total_men, int _total_women, int _total_activeusers, int _total_inactiveusers, int _total_logins, String _last_login, int _total_projects, int _total_activeprojects, int _total_inactiveprojects, String _last_project, int _total_tasks, int _total_started, int _total_paused, int _total_stoped, int _total_finished, int _total_inactive, int _total_urgent, int _total_high, int _total_medium, int _total_low, String _last_task)
  {
    total_users = _total_users;
    total_administrators = _total_administrators;
    total_normalusers = _total_normalusers;
    total_men = _total_men;
    total_women = _total_women;
    total_activeusers = _total_activeusers;
    total_inactiveusers = _total_inactiveusers;
    total_logins = _total_logins;
    last_login = _last_login;
    total_projects = _total_projects;
    total_activeprojects = _total_activeprojects;
    total_inactiveprojects = _total_inactiveprojects;
    last_project = _last_project;
    total_tasks = _total_tasks;
    total_started = _total_started;
    total_paused = _total_paused;
    total_stoped = _total_stoped;
    total_finished = _total_finished;
    total_inactive = _total_inactive;
    total_urgent = _total_urgent;
    total_high = _total_high;
    total_medium = _total_medium;
    total_low = _total_low;
    last_task = _last_task;
  } // ctor

} // class GeneralReportData
