package PMSystem;


/**
* PMSystem/MessagesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PMSystem.idl
* domingo 27 de noviembre de 2011 08H59' CST
*/

public final class MessagesHolder implements org.omg.CORBA.portable.Streamable
{
  public PMSystem.MessageData value[] = null;

  public MessagesHolder ()
  {
  }

  public MessagesHolder (PMSystem.MessageData[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PMSystem.MessagesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PMSystem.MessagesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PMSystem.MessagesHelper.type ();
  }

}
