package PMSystem;


/**
* PMSystem/MessageData.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PMSystem.idl
* domingo 27 de noviembre de 2011 08H59' CST
*/

public final class MessageData implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public int id_sender = (int)0;
  public int id_receiver = (int)0;
  public String sender = null;
  public String receiver = null;
  public String subject = null;
  public String message = null;
  public String date = null;
  public String state = null;

  public MessageData ()
  {
  } // ctor

  public MessageData (int _id, int _id_sender, int _id_receiver, String _sender, String _receiver, String _subject, String _message, String _date, String _state)
  {
    id = _id;
    id_sender = _id_sender;
    id_receiver = _id_receiver;
    sender = _sender;
    receiver = _receiver;
    subject = _subject;
    message = _message;
    date = _date;
    state = _state;
  } // ctor

} // class MessageData
