package PMSystem;

/**
* PMSystem/MessageDataHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PMSystem.idl
* domingo 27 de noviembre de 2011 08H59' CST
*/

public final class MessageDataHolder implements org.omg.CORBA.portable.Streamable
{
  public PMSystem.MessageData value = null;

  public MessageDataHolder ()
  {
  }

  public MessageDataHolder (PMSystem.MessageData initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PMSystem.MessageDataHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PMSystem.MessageDataHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PMSystem.MessageDataHelper.type ();
  }

}
