package PMSystem;

/**
* PMSystem/MessageHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PMSystem.idl
* domingo 27 de noviembre de 2011 08H59' CST
*/

public final class MessageHolder implements org.omg.CORBA.portable.Streamable
{
  public PMSystem.Message value = null;

  public MessageHolder ()
  {
  }

  public MessageHolder (PMSystem.Message initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PMSystem.MessageHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PMSystem.MessageHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PMSystem.MessageHelper.type ();
  }

}
