package PMSystem;

/**
* PMSystem/ProjectDataHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PMSystem.idl
* domingo 27 de noviembre de 2011 08H59' CST
*/

public final class ProjectDataHolder implements org.omg.CORBA.portable.Streamable
{
  public PMSystem.ProjectData value = null;

  public ProjectDataHolder ()
  {
  }

  public ProjectDataHolder (PMSystem.ProjectData initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PMSystem.ProjectDataHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PMSystem.ProjectDataHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PMSystem.ProjectDataHelper.type ();
  }

}
