package PMSystem;


/**
* PMSystem/ProjectOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PMSystem.idl
* domingo 27 de noviembre de 2011 08H59' CST
*/

public interface ProjectOperations 
{
  int setProject (int id_user, String name, String description, String start_date, String end_date, String state);
  int updateProject (int id, int id_user, String name, String description, String start_date, String end_date, String state);
  PMSystem.ProjectsBasicData[] getAllProjects ();
  PMSystem.ProjectData getProject (int id);
  PMSystem.ProjectData[] getProjects (String str);
  boolean trash (int id);
  boolean delete (int id);
  boolean restore (int id);
} // interface ProjectOperations
