package PMSystem;

/**
* PMSystem/TaskHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PMSystem.idl
* domingo 27 de noviembre de 2011 08H59' CST
*/

public final class TaskHolder implements org.omg.CORBA.portable.Streamable
{
  public PMSystem.Task value = null;

  public TaskHolder ()
  {
  }

  public TaskHolder (PMSystem.Task initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PMSystem.TaskHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PMSystem.TaskHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PMSystem.TaskHelper.type ();
  }

}
