package PMSystem;


/**
* PMSystem/TasksBasicData.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PMSystem.idl
* domingo 27 de noviembre de 2011 08H59' CST
*/

public final class TasksBasicData implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String title = null;

  public TasksBasicData ()
  {
  } // ctor

  public TasksBasicData (int _id, String _title)
  {
    id = _id;
    title = _title;
  } // ctor

} // class TasksBasicData
