package PMSystem;


/**
* PMSystem/TaskData.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PMSystem.idl
* domingo 27 de noviembre de 2011 08H59' CST
*/

public final class TaskData implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public int id_project = (int)0;
  public String project = null;
  public String users[] = null;
  public String title = null;
  public String description = null;
  public String start_date = null;
  public String end_date = null;
  public int progress = (int)0;
  public String priority = null;
  public String notes = null;
  public String state = null;

  public TaskData ()
  {
  } // ctor

  public TaskData (int _id, int _id_project, String _project, String[] _users, String _title, String _description, String _start_date, String _end_date, int _progress, String _priority, String _notes, String _state)
  {
    id = _id;
    id_project = _id_project;
    project = _project;
    users = _users;
    title = _title;
    description = _description;
    start_date = _start_date;
    end_date = _end_date;
    progress = _progress;
    priority = _priority;
    notes = _notes;
    state = _state;
  } // ctor

} // class TaskData
