package PMSystem;


/**
* PMSystem/UsersInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PMSystem.idl
* domingo 27 de noviembre de 2011 08H59' CST
*/

public final class UsersInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public PMSystem.UserData value[] = null;

  public UsersInfoHolder ()
  {
  }

  public UsersInfoHolder (PMSystem.UserData[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PMSystem.UsersInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PMSystem.UsersInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PMSystem.UsersInfoHelper.type ();
  }

}
