/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditTasksView.java
 *
 * Created on 05-nov-2011, 17:53:36
 */
package views;

import PMSystem.ProjectsBasicData;
import PMSystem.TaskData;
import PMSystem.TasksBasicData;
import PMSystem.UsersBasicData;
import controllers.MainController;
import controllers.TasksController;
import controllers.ProjectsController;
import controllers.UsersController;
import helpers.ComboBoxHelper;
import helpers.TimeHelper;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author Eduardo Figarola Mota <eduardofigarola@gmail.com>
 * @author Eneida Montserrat Sánchez Larios <eneida430@gmail.com>
 * @author Ana Alicia González Mendieta <anaglezmta@gmail.com>
 * @author Joel Hernández Gutiérrez <joel.hernandezg@gmail.com>
 */
public class EditTasksView extends AbstractIFrameView {
    
    private TasksController tasksController;
    private ProjectsController projectsController;
    private UsersController usersController;
    private TimeHelper timeHelper = new TimeHelper();
    private int ID_Task = 0;
    private boolean preventDefault = false;
    
    /** Creates new form EditTasksView */
    public EditTasksView(String args[]) {
        this.tasksController    = new TasksController(args);
        this.projectsController = new ProjectsController(args);
        this.usersController    = new UsersController(args);        
        initComponents();
    }
    
    public void translate() {
        jLabel1.setText(__("Edit Task"));
        jLabel10.setText(__("Priority:"));
        jLabel3.setText(__("Title:"));
        jLabel5.setText(__("Description:"));
        jLabel4.setText(__("Start date:"));
        jLabel6.setText(__("End date:"));
        jLabel7.setText(__("State:"));
        jLabel8.setText(__("Select a Project:"));
        jLabel9.setText(__("Progress:"));
        jLabel12.setText(__("Select a Task:"));
        jLabel11.setText(__("Users:"));
        jLabel13.setText(__("Return to home"));
        jButton1.setText(__("Edit Task"));
        jButton2.setText(__("Cancel"));        
    }
    
    public void configure(int id_task) {
        this.translate();
        
        TasksBasicData[] tasks = this.tasksController.getAllTasks();
        if(id_task == 0) {
            this.preventDefault = true;
        } else {
            this.preventDefault = false;
        }
        
        jComboBox5.removeAllItems();
        if(tasks != null) {
            for(int i = 0; i < tasks.length; i++) {
                ComboBoxHelper cbbh = new ComboBoxHelper(tasks[i].id, tasks[i].title);
                jComboBox5.addItem(cbbh);
                if(id_task > 0) {
                    if(id_task == tasks[i].id) {
                        jComboBox5.setSelectedIndex(i);
                    }
                } else {
                    jComboBox5.setSelectedIndex(-1);
                }
            }
        }
        
        UsersBasicData[] users = this.usersController.getAllUsers();
        jList1.removeAll();
        DefaultListModel listModel = new DefaultListModel();
        if(users != null) {
            for(int i = 0; i < users.length; i++) {
                ComboBoxHelper cbbh = new ComboBoxHelper(users[i].id, users[i].username);
                listModel.addElement(users[i].username);
            }
        }
        jList1.setModel(listModel);
        
        this.preventDefault = false;
        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jDateChooser2.setDateFormatString("yyyy-MM-dd");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jComboBox5 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        jLabel13 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();

        setMaximumSize(new java.awt.Dimension(1081, 630));
        setMinimumSize(new java.awt.Dimension(1081, 630));
        setPreferredSize(new java.awt.Dimension(1081, 630));

        jPanel1.setMaximumSize(new java.awt.Dimension(1081, 630));
        jPanel1.setMinimumSize(new java.awt.Dimension(1081, 630));
        jPanel1.setPreferredSize(new java.awt.Dimension(1081, 630));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel4.setText("Start date:");

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel10.setText("Priority:");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel3.setText("Title:");

        jTextField1.setFont(new java.awt.Font("Verdana", 1, 14));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel5.setText("Description:");

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel7.setText("State:");

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel8.setText("Select Project:");

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel6.setText("End date:");

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel12.setText("Select Task:");

        jComboBox2.setFont(new java.awt.Font("Verdana", 1, 14));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Started", "Paused", "Stoped", "Finished", "Inactive" }));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18));
        jLabel1.setText("Edit Task");

        jComboBox4.setFont(new java.awt.Font("Verdana", 1, 14));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Urgent", "High", "Medium", "Low" }));

        jComboBox3.setFont(new java.awt.Font("Verdana", 1, 14));

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel11.setText("Users:");

        jList1.setFont(new java.awt.Font("Verdana", 1, 14));
        jScrollPane3.setViewportView(jList1);

        jComboBox5.setFont(new java.awt.Font("Verdana", 1, 14));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton1.setText("Edit Task");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Verdana", 1, 14));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel9.setText("Progress:");

        jButton2.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jSlider1.setFont(new java.awt.Font("Verdana", 1, 14));
        jSlider1.setMajorTickSpacing(20);
        jSlider1.setMinorTickSpacing(10);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setValue(0);

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel13.setForeground(new java.awt.Color(14, 137, 254));
        jLabel13.setText("Return to home");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jDateChooser1.setFont(new java.awt.Font("Verdana", 1, 14));

        jDateChooser2.setFont(new java.awt.Font("Verdana", 1, 14));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1)
                            .addComponent(jScrollPane1)
                            .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 864, Short.MAX_VALUE)
                        .addComponent(jLabel13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel1))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(jLabel11))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(148, 148, 148))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        if(evt.getSource() == jComboBox5 && !this.preventDefault) {
            ComboBoxHelper dataTask = (ComboBoxHelper) jComboBox5.getSelectedItem();
            TaskData task = this.tasksController.getTask(dataTask.getID());
            
            //Select the project of the task from the combobox
            ProjectsBasicData[] projects = this.projectsController.getAllProjects();
            jComboBox3.removeAllItems();
            if(projects != null) {
                for(int i = 0; i < projects.length; i++) {
                    ComboBoxHelper cbbh = new ComboBoxHelper(projects[i].id, projects[i].name);
                    jComboBox3.addItem(cbbh);
                    if(task.id_project == projects[i].id) {
                        jComboBox3.setSelectedIndex(i);
                    }
                }
            }
            
            //Select the users of the task from the jlist
            UsersBasicData[] users = this.usersController.getAllUsers();
            ArrayList selected = new ArrayList();
            int[] iUsers = new int[task.users.length];
            for(int j = 0; j < users.length; j++) {
                for(int k = 0; k < task.users.length; k++) {
                    if(task.users[k].equals(users[j].username)) {
                        selected.add(j);
                    }
                }
            }
            
            for(int l = 0; l < iUsers.length; l++) {
                iUsers[l] = Integer.parseInt(selected.get(l).toString());
            }
            
            jList1.setSelectedIndices(iUsers);            
            
            //Set all the other fields
            this.ID_Task = task.id;
            jTextField1.setText(task.title);
            jTextArea1.setText(task.description);
            jDateChooser1.setDate(Date.valueOf(task.start_date));
            jDateChooser2.setDate(Date.valueOf(task.end_date));
            jSlider1.setValue(task.progress);
            jComboBox4.setSelectedItem(task.priority);
            jComboBox2.setSelectedItem(task.state);
       }
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String title       = jTextField1.getText();
        String description = jTextArea1.getText();
        String start_date  = this.timeHelper.getDateString(jDateChooser1.getDate());
        String end_date    = this.timeHelper.getDateString(jDateChooser2.getDate());
        int progress       = jSlider1.getValue();
        String priority    = jComboBox4.getSelectedItem().toString();
        String state       = jComboBox2.getSelectedItem().toString();
        
        int ID_Project;
        try {
            ComboBoxHelper dataProject = (ComboBoxHelper) jComboBox3.getSelectedItem();
            ID_Project = dataProject.getID();
        } catch(Exception e) {
            ID_Project = 0;
        }
            
        String[] users;
        Object[] listUsers;
        
        listUsers = jList1.getSelectedValues();
        users = new String[listUsers.length];
        
        for(int i = 0; i < listUsers.length; i++) {
            users[i] = listUsers[i].toString();
        }
              
        String[] result = this.tasksController.editTask(this.ID_Task, ID_Project, users, title, description, start_date, end_date, progress, priority, state);
        
        this.alertsHelper.showAlert(__(result[0]), result[1]);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextField1.setText("");
        jDateChooser1.setDate(null);
        jDateChooser2.setDate(null);
        jTextArea1.setText("");
        jSlider1.setValue(0);
        jList1.setSelectedValue("", false);
        jComboBox3.setSelectedIndex(-1);
        jComboBox2.setSelectedIndex(0);
        jComboBox4.setSelectedIndex(0);
        this.preventDefault = true;
        jComboBox5.setSelectedIndex(-1);
        this.preventDefault = false;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        if(evt.getButton() == 1) {
            MainController.adminView.home();
        }
    }//GEN-LAST:event_jLabel13MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}