/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GeneralReportView.java
 *
 * Created on 11-nov-2011, 0:12:11
 */
package views;

import controllers.ReportsController;
import PMSystem.GeneralReportData;
import controllers.MainController;

/**
 *
 * @author Eduardo Figarola Mota <eduardofigarola@gmail.com>
 * @author Eneida Montserrat Sánchez Larios <eneida430@gmail.com>
 * @author Ana Alicia González Mendieta <anaglezmta@gmail.com>
 * @author Joel Hernández Gutiérrez <joel.hernandezg@gmail.com>
 */
public class GeneralReportView extends AbstractIFrameView {
    
    private ReportsController reportsController;
    
    /** Creates new form GeneralReportView */
    public GeneralReportView(String args[]) {
        this.reportsController = new ReportsController(args);
        initComponents();
    }
    
    public void translate() {
        jLabel1.setText(__("General Report"));
        jLabel2.setText(__("» Users"));
        jLabel3.setText(__("» Registered users:"));
        jLabel4.setText(__("» Administrators:"));
        jLabel5.setText(__("» Normal users:"));
        jLabel6.setText(__("» Men:"));
        jLabel7.setText(__("» Women:"));
        jLabel8.setText(__("» Active:"));
        jLabel9.setText(__("» Inactive:"));
        jLabel10.setText(__("» Logins:"));
        jLabel11.setText(__("» Last login:"));
        jLabel12.setText(__("» Projects"));
        jLabel13.setText(__("» Total projects:"));
        jLabel14.setText(__("» Active:"));
        jLabel15.setText(__("» Inactive:"));
        jLabel16.setText(__("» Last project:"));
        jLabel17.setText(__("» Tasks"));
        jLabel18.setText(__("» Total tasks:"));
        jLabel19.setText(__("» Started:"));
        jLabel20.setText(__("» Inactive:"));
        jLabel21.setText(__("» Last task:"));
        jLabel22.setText(__("» Paused:"));
        jLabel23.setText(__("» Stopped:"));
        jLabel24.setText(__("» Finished:"));
        jLabel25.setText(__("» Urgent priority:"));
        jLabel26.setText(__("» High priority:"));
        jLabel27.setText(__("» Low priority:"));
        jLabel28.setText(__("» Medium priority:"));
        jLabel29.setText(__("Return to home"));        
    }
    
    public void configure() {
        this.translate();
        
        GeneralReportData report = this.reportsController.getGeneralReport();
        
        jLabel3.setText(jLabel3.getText()+" "+report.total_users);
        jLabel4.setText(jLabel4.getText()+" "+report.total_administrators);
        jLabel5.setText(jLabel5.getText()+" "+report.total_normalusers);
        jLabel6.setText(jLabel6.getText()+" "+report.total_men);
        jLabel7.setText(jLabel7.getText()+" "+report.total_women);
        jLabel8.setText(jLabel8.getText()+" "+report.total_activeusers);
        jLabel9.setText(jLabel9.getText()+" "+report.total_inactiveusers);
        jLabel10.setText(jLabel10.getText()+" "+report.total_logins);
        jLabel11.setText(jLabel11.getText()+" "+report.last_login);
        
        jLabel13.setText(jLabel13.getText()+" "+report.total_projects);
        jLabel14.setText(jLabel14.getText()+" "+report.total_activeprojects);
        jLabel15.setText(jLabel15.getText()+" "+report.total_inactiveprojects);
        jLabel16.setText(jLabel16.getText()+" "+report.last_project);
        
        jLabel18.setText(jLabel18.getText()+" "+report.total_tasks);
        jLabel19.setText(jLabel19.getText()+" "+report.total_started);
        jLabel22.setText(jLabel22.getText()+" "+report.total_paused);
        jLabel23.setText(jLabel23.getText()+" "+report.total_stoped);
        jLabel24.setText(jLabel24.getText()+" "+report.total_finished);
        jLabel20.setText(jLabel20.getText()+" "+report.total_inactive);
        jLabel25.setText(jLabel25.getText()+" "+report.total_urgent);
        jLabel26.setText(jLabel26.getText()+" "+report.total_high);
        jLabel28.setText(jLabel28.getText()+" "+report.total_medium);
        jLabel27.setText(jLabel27.getText()+" "+report.total_low);
        jLabel21.setText(jLabel21.getText()+" "+report.last_task);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1081, 630));
        setMinimumSize(new java.awt.Dimension(1081, 630));
        setPreferredSize(new java.awt.Dimension(1081, 630));

        jPanel1.setMaximumSize(new java.awt.Dimension(1081, 630));
        jPanel1.setMinimumSize(new java.awt.Dimension(1081, 630));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18));
        jLabel1.setText("General Report");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 15));
        jLabel2.setForeground(new java.awt.Color(14, 137, 254));
        jLabel2.setText("» Users");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 15));
        jLabel3.setText("» Registered users: ");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 15));
        jLabel4.setText("» Administrators: ");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 15));
        jLabel5.setText("» Normal users: ");

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 15));
        jLabel6.setText("» Men: ");

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 15));
        jLabel7.setText("» Women: ");

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 15));
        jLabel8.setText("» Active: ");

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 15));
        jLabel9.setText("» Inactive: ");

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 15));
        jLabel10.setText("» Logins: ");

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 15));
        jLabel11.setText("» Last login: ");

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 15));
        jLabel12.setForeground(new java.awt.Color(14, 137, 254));
        jLabel12.setText("» Projects");

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 15));
        jLabel13.setText("» Total projects: ");

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 15));
        jLabel14.setText("» Active: ");

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 15));
        jLabel15.setText("» Inactive: ");

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 15));
        jLabel16.setText("» Last project: ");

        jLabel17.setFont(new java.awt.Font("Verdana", 1, 15));
        jLabel17.setForeground(new java.awt.Color(14, 137, 254));
        jLabel17.setText("» Tasks");

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 15));
        jLabel18.setText("» Total tasks: ");

        jLabel19.setFont(new java.awt.Font("Verdana", 1, 15));
        jLabel19.setText("» Started: ");

        jLabel20.setFont(new java.awt.Font("Verdana", 1, 15));
        jLabel20.setText("» Inactive: ");

        jLabel21.setFont(new java.awt.Font("Verdana", 1, 15));
        jLabel21.setText("» Last task: ");

        jLabel22.setFont(new java.awt.Font("Verdana", 1, 15));
        jLabel22.setText("» Paused: ");

        jLabel23.setFont(new java.awt.Font("Verdana", 1, 15));
        jLabel23.setText("» Stoped: ");

        jLabel24.setFont(new java.awt.Font("Verdana", 1, 15));
        jLabel24.setText("» Finished: ");

        jLabel25.setFont(new java.awt.Font("Verdana", 1, 15));
        jLabel25.setText("» Urgent priority: ");

        jLabel26.setFont(new java.awt.Font("Verdana", 1, 15));
        jLabel26.setText("» High priority: ");

        jLabel27.setFont(new java.awt.Font("Verdana", 1, 15));
        jLabel27.setText("» Low priority: ");

        jLabel28.setFont(new java.awt.Font("Verdana", 1, 15));
        jLabel28.setText("» Medium priority: ");

        jLabel29.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(14, 137, 254));
        jLabel29.setText("Return to home");
        jLabel29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)))
                            .addComponent(jLabel12)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))))
                        .addGap(189, 189, 189)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel21))))
                        .addGap(198, 198, 198))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 702, Short.MAX_VALUE)
                        .addComponent(jLabel29)
                        .addGap(113, 113, 113))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)))))
                .addContainerGap(188, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        if(evt.getButton() == 1) {
            MainController.adminView.home();
        }
    }//GEN-LAST:event_jLabel29MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}