/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainAdminView.java
 *
 * Created on 23-oct-2011, 0:10:38
 */
package views;

import controllers.MainController;
import controllers.UsersController;
import controllers.MessagesController;
import helpers.TimeHelper;

/**
 *
 * @author Eduardo Figarola Mota <eduardofigarola@gmail.com>
 * @author Eneida Montserrat Sánchez Larios <eneida430@gmail.com>
 * @author Ana Alicia González Mendieta <anaglezmta@gmail.com>
 * @author Joel Hernández Gutiérrez <joel.hernandezg@gmail.com>
 */
public class MainAdminView extends AbstractJFrameView {

    private static String orbdConfig[];
    
    private class NewMessagesUpdater implements Runnable {
        
        private MessagesController messagesController;
        private int newMessages = 0;
        
        public NewMessagesUpdater(String args[]) {
            messagesController = new MessagesController(args);
        }
        
        @Override
        public void run() {
            while(true) {
                this.newMessages = this.messagesController.countNewMessages(MainController.userOnlineID);
                if(this.newMessages > 0) {
                    jMenu7.setText(__("Messages") + " ("+this.newMessages+")");
                } else {
                    jMenu7.setText(__("Messages"));
                }
                
                try {
                    Thread.sleep(30000);
                } catch(Exception e) {
                    
                }
            }
            
        }
    }
    
    private UsersController usersController;
    private TimeHelper timeHelper = new TimeHelper();
    private AdminHomeView adminHomeView;
    private SaveUsersView saveUsersView;
    private EditUsersView editUsersView;
    private SaveProjectsView saveProjectsView;
    private EditProjectsView editProjectsView;
    private SaveTasksView saveTasksView;
    private EditTasksView editTasksView;
    private FindUsersMainView findUsersMainView;
    private FindProjectsMainView findProjectsMainView;
    private FindTasksMainAdminView findTasksMainView;
    private EditUserProfileView editUserProfileView;
    private EditTaskProgressView editTaskProgress;
    private GeneralReportView generalReportView;
    private FindUsersOnlineView findUsersOnline;
    private SendMessageView sendMessageView;
    private FindMyMessagesView findMyMessages;
    private ReadMessageView readMessageView;
    private GanttReport ganttReport;
    private LoginsProyection loginsProyection;
    private SetConfigurationView setConfigurationView;

    
    /** Creates new form Main */
    public MainAdminView(String args[]) {
        MainAdminView.orbdConfig = args;
        usersController = new UsersController(args);
        setTitle("Project.me System");
        setTheme(MainController.getTheme());        
        initComponents();
        this.translate();
        this.setSize(1100, 700);
        NewMessagesUpdater newMessagesUpdater = new NewMessagesUpdater(args);
        Thread updater = new Thread(newMessagesUpdater);
        updater.start();
        center();
        this.setVisible(true);
        this.home();
    }
    
    public void translate() {
        jMenu1.setText(__("Users"));
        jMenu2.setText(__("Projects"));
        jMenu3.setText(__("Tasks"));
        jMenu4.setText(__("Help"));
        jMenu5.setText(__("Home"));
        jMenu6.setText(__("Reports"));
        jMenu7.setText(__("Messages"));
        
        jMenuItem12.setText(__("Home"));
        jMenuItem13.setText(__("Edit profile"));
        jMenuItem17.setText(__("View online users"));
        jMenuItem14.setText(__("Log out"));
        jMenuItem15.setText(__("Close"));
        jMenuItem1.setText(__("New"));
        jMenuItem2.setText(__("Edit"));
        jMenuItem7.setText(__("Find"));
        jMenuItem3.setText(__("New"));
        jMenuItem4.setText(__("Edit"));
        jMenuItem8.setText(__("Find"));
        jMenuItem5.setText(__("New"));
        jMenuItem6.setText(__("Edit"));
        jMenuItem9.setText(__("Find"));
        jMenuItem16.setText(__("General"));
        jMenuItem18.setText(__("New"));
        jMenuItem19.setText(__("My Messages"));
        jMenuItem10.setText(__("Help"));
        jMenuItem11.setText(__("About..."));       
        jMenuItem21.setText(__("Logins Proyection")); 
        jMenuItem22.setText(__("Configuration")); 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setMaximumSize(new java.awt.Dimension(1024, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 600));
        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu5.setText("Home");

        jMenuItem12.setText("Home");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem12);

        jMenuItem13.setText("Edit profile");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem13);

        jMenuItem17.setText("View online users");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem17);
        jMenu5.add(jSeparator2);

        jMenuItem14.setText("Log out");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem14);

        jMenuItem15.setText("Close");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem15);

        jMenuBar1.add(jMenu5);

        jMenu1.setText("Users");

        jMenuItem1.setText("New");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Edit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem7.setText("Find");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Projects");

        jMenuItem3.setText("New");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Edit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem8.setText("Find");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Tasks");

        jMenuItem5.setText("New");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText("Edit");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem9.setText("Find");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuBar1.add(jMenu3);

        jMenu6.setText("Reports");

        jMenuItem16.setText("General");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem16);

        jMenuItem20.setText("Gantt");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem20);

        jMenuItem21.setText("Logins Proyection");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem21);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Messages");

        jMenuItem18.setText("New");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem18);

        jMenuItem19.setText("My Messages");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem19);

        jMenuBar1.add(jMenu7);

        jMenu4.setText("Help");

        jMenuItem10.setText("Help");
        jMenu4.add(jMenuItem10);
        jMenu4.add(jSeparator1);

        jMenuItem22.setText("Configuration");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem22);

        jMenuItem11.setText("About...");
        jMenu4.add(jMenuItem11);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void home() {
        adminHomeView = new AdminHomeView(orbdConfig);
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(adminHomeView);
        adminHomeView.configure();
        adminHomeView.pack();
        adminHomeView.setVisible(true);
    }
    
    public void saveUser() {
        saveUsersView = new SaveUsersView(orbdConfig);
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(saveUsersView);
        saveUsersView.configure();
        saveUsersView.pack();
        saveUsersView.setVisible(true);
    }
    
    public void editUser(int id_user) {
        editUsersView = new EditUsersView(orbdConfig);
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(editUsersView);
        editUsersView.configure(id_user);
        editUsersView.pack();
        editUsersView.setVisible(true); 
    }
    
    public void editProfile() {
        editUserProfileView = new EditUserProfileView(orbdConfig);
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(editUserProfileView);
        editUserProfileView.configure();
        editUserProfileView.pack();
        editUserProfileView.setVisible(true); 
    }
    
    public void saveProject() {
        saveProjectsView = new SaveProjectsView(orbdConfig);
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(saveProjectsView);
        saveProjectsView.configure();
        saveProjectsView.pack();
        saveProjectsView.setVisible(true);
    }
    
    public void editProject(int id_project) {
        editProjectsView = new EditProjectsView(orbdConfig);
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(editProjectsView);
        editProjectsView.configure(id_project);
        editProjectsView.pack();
        editProjectsView.setVisible(true);
    }
    
    public void saveTask() {
        saveTasksView = new SaveTasksView(orbdConfig);
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(saveTasksView);
        saveTasksView.configure();
        saveTasksView.pack();
        saveTasksView.setVisible(true);
    }
    
    public void editTask(int id_task) {
        editTasksView = new EditTasksView(orbdConfig);
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(editTasksView);
        editTasksView.configure(id_task);
        editTasksView.pack();
        editTasksView.setVisible(true);
    }
    
    public void updateTaskProgress(int id_task) {
        editTaskProgress = new EditTaskProgressView(orbdConfig);
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(editTaskProgress);
        editTaskProgress.configure(id_task);
        editTaskProgress.pack();
        editTaskProgress.setVisible(true);
    }
    
    public void findUsers() {
        findUsersMainView = new FindUsersMainView(orbdConfig);
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(findUsersMainView);
        findUsersMainView.configure();
        findUsersMainView.pack();
        findUsersMainView.setVisible(true);
    }
    
    public void findProjects() {
        findProjectsMainView = new FindProjectsMainView(orbdConfig);
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(findProjectsMainView);
        findProjectsMainView.configure();
        findProjectsMainView.pack();
        findProjectsMainView.setVisible(true);
    }
    
    public void findTasks() {
        findTasksMainView = new FindTasksMainAdminView(orbdConfig);
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(findTasksMainView);
        findTasksMainView.configure();
        findTasksMainView.pack();
        findTasksMainView.setVisible(true);
    }
    
    public void generalReport() {
        generalReportView = new GeneralReportView(orbdConfig);
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(generalReportView);
        generalReportView.configure();
        generalReportView.pack();
        generalReportView.setVisible(true);
    }
   
    public void usersOnline() {
        findUsersOnline = new FindUsersOnlineView(orbdConfig);
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(findUsersOnline);
        findUsersOnline.configure();
        findUsersOnline.pack();
        findUsersOnline.setVisible(true);
    }
    
    public void sendMessage(int id_user) {
        sendMessageView = new SendMessageView(orbdConfig);
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(sendMessageView);
        sendMessageView.configure(id_user);
        sendMessageView.pack();
        sendMessageView.setVisible(true);
    }
    
    public void readMessage(int id_message) {
        readMessageView = new ReadMessageView(orbdConfig);
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(readMessageView);
        readMessageView.configure(id_message);
        readMessageView.pack();
        readMessageView.setVisible(true);
    }
    
    public void myMessages() {
        findMyMessages = new FindMyMessagesView(orbdConfig);
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(findMyMessages);
        findMyMessages.configure();
        findMyMessages.pack();
        findMyMessages.setVisible(true);
    }
    
    public void getGanttReport(int id) {
        ganttReport = new GanttReport(orbdConfig);
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(ganttReport);
        ganttReport.configure(id);
        ganttReport.pack();
        ganttReport.setVisible(true);
    }
    
    public void getLoginsProyection() {
        loginsProyection = new LoginsProyection(orbdConfig);
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(loginsProyection);
        loginsProyection.configure();
        loginsProyection.pack();
        loginsProyection.setVisible(true);
    }
    
    public void configuration() {
        setConfigurationView = new SetConfigurationView(orbdConfig);
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(setConfigurationView);
        setConfigurationView.configure();
        setConfigurationView.pack();
        setConfigurationView.setVisible(true);
    }
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.saveUser();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.editUser(0);        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.saveProject();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.editProject(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        this.saveTask();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        this.editTask(0);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        this.findUsers();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        this.findProjects();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        this.findTasks();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        this.usersController.logout(MainController.userOnlineID, this.timeHelper.getActualTime());
        MainController mainController = new MainController(orbdConfig, true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        this.usersController.logout(MainController.userOnlineID, this.timeHelper.getActualTime());
        System.exit(0);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        this.editProfile();
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        this.home();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        this.generalReport();
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.usersController.logout(MainController.userOnlineID, this.timeHelper.getActualTime());
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        this.usersOnline();
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        this.sendMessage(0);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        this.myMessages();
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        this.getGanttReport(0);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        this.getLoginsProyection();
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        this.configuration();
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    /**
     * @param args the command line arguments
     */
    //public void init(final String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainAdminView(args).setVisible(true);
            }
        });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}