/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainAdminView.java
 *
 * Created on 23-oct-2011, 0:10:38
 */
package views;

import controllers.MainController;
import controllers.MessagesController;
import controllers.UsersController;
import helpers.TimeHelper;

/**
 *
 * @author Eduardo Figarola Mota <eduardofigarola@gmail.com>
 * @author Eneida Montserrat Sánchez Larios <eneida430@gmail.com>
 * @author Ana Alicia González Mendieta <anaglezmta@gmail.com>
 * @author Joel Hernández Gutiérrez <joel.hernandezg@gmail.com>
 */
public class MainUserView extends AbstractJFrameView {
    
    private class NewMessagesUpdater implements Runnable {
        private MessagesController messagesController;
        private int newMessages = 0;
        
        public NewMessagesUpdater(String args[]) {
            messagesController = new MessagesController(args);
        }
        
        @Override
        public void run() {
            while(true) {
                this.newMessages = this.messagesController.countNewMessages(MainController.userOnlineID);
                if(this.newMessages > 0) {
                    jMenu4.setText("Messages ("+this.newMessages+")");
                } else {
                    jMenu4.setText("Messages");
                }
                
                try {
                    Thread.sleep(30000);
                } catch(Exception e) {
                    
                }
            }
            
        }
    }
    
    private static String orbdConfig[];
    private EditUserProfileView editUserProfileView;
    private EditTaskProgressView editTaskProgress;
    private FindMyTasksUserView findMyTasksUser;
    private FindUsersOnlineView findUsersOnline;
    private SendMessageView sendMessageView;
    private ReadMessageView readMessageView;
    private FindMyMessagesView findMyMessages;
    private UsersController usersController;
    private TimeHelper timeHelper = new TimeHelper();
    private UserHomeView userHomeView;
    
    /** Creates new form Main */
    public MainUserView(String args[]) {
        MainUserView.orbdConfig = args;
        this.usersController = new UsersController(args);
        setTitle("Project.me System");
        setTheme(1);
        
        initComponents();
        this.translate();
        this.setSize(1100, 700);
        NewMessagesUpdater newMessagesUpdater = new NewMessagesUpdater(args);
        Thread updater = new Thread(newMessagesUpdater);
        updater.start();
        center();
        this.setVisible(true); 
        this.home();
    }
    
    public void translate() {
        jMenu1.setText(__("Home"));
        jMenu2.setText(__("Tasks"));
        jMenu3.setText(__("Help"));
        jMenu4.setText(__("Messages"));
        jMenuItem1.setText(__("Home"));
        jMenuItem2.setText(__("Edit profile"));
        jMenuItem3.setText(__("My Tasks"));
        jMenuItem4.setText(__("About..."));
        jMenuItem5.setText(__("Help"));
        jMenuItem6.setText(__("View online users"));
        jMenuItem7.setText(__("Log out"));
        jMenuItem8.setText(__("New"));
        jMenuItem9.setText(__("My Messages"));
        jMenuItem10.setText(__("Close"));        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setMaximumSize(new java.awt.Dimension(1024, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 600));
        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Home");

        jMenuItem1.setText("Home");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Edit Profile");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem6.setText("View online users");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);
        jMenu1.add(jSeparator1);

        jMenuItem7.setText("Log out");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem10.setText("Close");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tasks");

        jMenuItem3.setText("My Tasks");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Messages");

        jMenuItem8.setText("New");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuItem9.setText("My Messages");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Help");

        jMenuItem5.setText("Help");
        jMenu3.add(jMenuItem5);
        jMenu3.add(jSeparator2);

        jMenuItem4.setText("About...");
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void home() {
        userHomeView = new UserHomeView(orbdConfig);
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(userHomeView);
        userHomeView.configure();
        userHomeView.pack();
        userHomeView.setVisible(true);
    }
  
    public void editProfile() {
        editUserProfileView = new EditUserProfileView(orbdConfig);
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(editUserProfileView);
        editUserProfileView.configure();
        editUserProfileView.pack();
        editUserProfileView.setVisible(true); 
    }

    public void updateTaskProgress(int id_task) {
        editTaskProgress = new EditTaskProgressView(orbdConfig);
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(editTaskProgress);
        editTaskProgress.configure(id_task);
        editTaskProgress.pack();
        editTaskProgress.setVisible(true);
    }
    
    public void usersOnline() {
        findUsersOnline = new FindUsersOnlineView(orbdConfig);
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(findUsersOnline);
        findUsersOnline.configure();
        findUsersOnline.pack();
        findUsersOnline.setVisible(true);
    }
    
    public void myTasks() {
        findMyTasksUser = new FindMyTasksUserView(orbdConfig);
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(findMyTasksUser);
        findMyTasksUser.configure();
        findMyTasksUser.pack();
        findMyTasksUser.setVisible(true);
    }
    
    public void sendMessage(int id_user) {
        sendMessageView = new SendMessageView(orbdConfig);
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(sendMessageView);
        sendMessageView.configure(id_user);
        sendMessageView.pack();
        sendMessageView.setVisible(true);
    }
    
    public void readMessage(int id_message) {
        readMessageView = new ReadMessageView(orbdConfig);
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(readMessageView);
        readMessageView.configure(id_message);
        readMessageView.pack();
        readMessageView.setVisible(true);
    }
    
    public void myMessages() {
        findMyMessages = new FindMyMessagesView(orbdConfig);
        this.jDesktopPane1.removeAll();
        this.jDesktopPane1.add(findMyMessages);
        findMyMessages.configure();
        findMyMessages.pack();
        findMyMessages.setVisible(true);
    }
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.home();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.editProfile();      
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        this.usersController.logout(MainController.userOnlineID, this.timeHelper.getActualTime());
        MainController mainController = new MainController(orbdConfig, true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        this.usersController.logout(MainController.userOnlineID, this.timeHelper.getActualTime());
        System.exit(0);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.myTasks();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        this.usersOnline();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        this.sendMessage(0);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        this.myMessages();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.usersController.logout(MainController.userOnlineID, this.timeHelper.getActualTime());
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}